#############################################################################
# Makefile for building: CPSC589A1.app/Contents/MacOS/CPSC589A1
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  CPSC589A1.pro
# Template: app
# Command: /Applications/QT/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile CPSC589A1.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/Applications/QT/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.7/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/QT/5.7/clang_64/mkspecs/macx-clang -F/Applications/QT/5.7/clang_64/lib
QMAKE         = /Applications/QT/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CPSC589A11.0.0
DISTDIR = /Users/bemayer/Documents/CPSC589A1/.tmp/CPSC589A11.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Applications/QT/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/QT/5.7/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		renderer.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		renderer.o \
		moc_mainwindow.o
DIST          = /Applications/QT/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.7/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.7/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.7/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.7/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/QT/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/toolchain.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/qt.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/resources.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/moc.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/uic.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/lex.prf \
		CPSC589A1.pro mainwindow.h \
		renderer.h main.cpp \
		mainwindow.cpp \
		renderer.cpp
QMAKE_TARGET  = CPSC589A1
DESTDIR       = 
TARGET        = CPSC589A1.app/Contents/MacOS/CPSC589A1


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d CPSC589A1.app/Contents/MacOS/ || mkdir -p CPSC589A1.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CPSC589A1.pro /Applications/QT/5.7/clang_64/mkspecs/macx-clang/qmake.conf /Applications/QT/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.7/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.7/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.7/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.7/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.7/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/QT/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/toolchain.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/qt.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/resources.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/moc.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/uic.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.7/clang_64/mkspecs/features/lex.prf \
		CPSC589A1.pro \
		/Applications/QT/5.7/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/QT/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/QT/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile CPSC589A1.pro
/Applications/QT/5.7/clang_64/mkspecs/features/spec_pre.prf:
/Applications/QT/5.7/clang_64/mkspecs/qdevice.pri:
/Applications/QT/5.7/clang_64/mkspecs/features/device_config.prf:
/Applications/QT/5.7/clang_64/mkspecs/common/unix.conf:
/Applications/QT/5.7/clang_64/mkspecs/common/mac.conf:
/Applications/QT/5.7/clang_64/mkspecs/common/macx.conf:
/Applications/QT/5.7/clang_64/mkspecs/common/sanitize.conf:
/Applications/QT/5.7/clang_64/mkspecs/common/gcc-base.conf:
/Applications/QT/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/QT/5.7/clang_64/mkspecs/common/clang.conf:
/Applications/QT/5.7/clang_64/mkspecs/common/clang-mac.conf:
/Applications/QT/5.7/clang_64/mkspecs/qconfig.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/QT/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/QT/5.7/clang_64/mkspecs/features/qt_functions.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/qt_config.prf:
/Applications/QT/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/QT/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Applications/QT/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/toolchain.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/mac/toolchain.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/default_pre.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/resolve_config.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/default_post.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/qml_debug.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/warn_on.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/qt.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/resources.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/moc.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/uic.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/unix/thread.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/file_copies.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/mac/rez.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/exceptions.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/yacc.prf:
/Applications/QT/5.7/clang_64/mkspecs/features/lex.prf:
CPSC589A1.pro:
/Applications/QT/5.7/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/QT/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/QT/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile CPSC589A1.pro

qmake_all: FORCE

CPSC589A1.app/Contents/PkgInfo: 
	@test -d CPSC589A1.app/Contents || mkdir -p CPSC589A1.app/Contents
	@$(DEL_FILE) CPSC589A1.app/Contents/PkgInfo
	@echo "APPL????" > CPSC589A1.app/Contents/PkgInfo
CPSC589A1.app/Contents/Resources/empty.lproj: 
	@test -d CPSC589A1.app/Contents/Resources || mkdir -p CPSC589A1.app/Contents/Resources
	@touch CPSC589A1.app/Contents/Resources/empty.lproj
	
CPSC589A1.app/Contents/Info.plist: 
	@test -d CPSC589A1.app/Contents || mkdir -p CPSC589A1.app/Contents
	@$(DEL_FILE) CPSC589A1.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,berniemayer.CPSC589A1,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,CPSC589A1,g" -e "s,@LIBRARY@,CPSC589A1,g" -e "s,@TYPEINFO@,????,g" /Applications/QT/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >CPSC589A1.app/Contents/Info.plist

all: Makefile \
		CPSC589A1.app/Contents/PkgInfo \
		CPSC589A1.app/Contents/Resources/empty.lproj \
		CPSC589A1.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h renderer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp renderer.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CPSC589A1.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		mainwindow.h \
		/Applications/QT/5.7/clang_64/bin/moc
	/Applications/QT/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/QT/5.7/clang_64/mkspecs/macx-clang -I/Users/bemayer/Documents/CPSC589A1 -I/Users/bemayer/Documents/CPSC589A1 -I/Applications/QT/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.7/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/QT/5.7/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Applications/QT/5.7/clang_64/bin/uic \
		renderer.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		common/shader.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers/OpenGL.h
	/Applications/QT/5.7/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		ui_mainwindow.h \
		renderer.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		common/shader.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers/OpenGL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

renderer.o: renderer.cpp renderer.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Applications/QT/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_sse2.inl \
		glm/detail/type_vec4_avx.inl \
		glm/detail/type_vec4_avx2.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		common/shader.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers/OpenGL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderer.o renderer.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

